// Generated by CoffeeScript 1.7.1
var CastTesk, agentName, serverUrl, system, webpage, websocket, _onError;

system = require("system");

webpage = require("webpage");

if (system.args.length !== 3) {
  console.log('serverUrl and agentName is necessary!');
  phantom.exit(1);
}

agentName = system.args[1];

serverUrl = system.args[2];

_onError = function(msg, trace) {
  var msgStack;
  msgStack = [msg];
  if (trace) {
    trace.forEach(function(t) {
      var _ref;
      return msgStack.push(" -> " + t.file + ": " + t.line + ((_ref = t["function"]) != null ? _ref : " (in function '" + t["function"] + {
        "')": ""
      }));
    });
  }
  return console.log(msgStack.join("\n"));
};

websocket = webpage.create();

websocket.settings.localToRemoteUrlAccessEnabled = true;

websocket.onConsoleMessage = function(info) {
  return console.log("~Websocket: " + info);
};

websocket.onError = _onError;

websocket.onCallback = function(info) {
  switch (info.command) {
    case "CastTesk":
      return CastTesk(info.task);
  }
};

websocket.injectJs('./jquery-2.1.0.min.js');

websocket.injectJs('./jquery.signalR-2.0.2.min.js');

websocket.includeJs(serverUrl + '/signalr/hubs', function() {
  return websocket.evaluate(function(serverUrl, agentName) {
    var taskHub;
    $.support.cors = false;
    $.connection.hub.url = serverUrl + '/signalr';
    taskHub = $.connection.taskHub;
    taskHub.client.castTesk = function(task) {
      return window.callPhantom({
        command: "CastTesk",
        task: task
      });
    };
    return $.connection.hub.start().done(function() {
      $.support.cors = true;
      return taskHub.server.registerAgent(agentName);
    }).fail(function(msg) {
      return console.log('connect fail. ' + msg);
    });
  }, serverUrl, agentName);
});

CastTesk = function(task) {
  var gbdate, now, pageGrab;
  console.log("~CastTesk: " + JSON.stringify(task));
  pageGrab = webpage.create();
  pageGrab.settings.userAgent = 'Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/27.0.1453.93 Safari/537.36';
  pageGrab.settings.loadImages = false;
  now = Date.now();
  gbdate = {};
  pageGrab.onConsoleMessage = function(msg) {
    return console.log('~Evaluate: ' + msg);
  };
  pageGrab.onError = function(msg, trace) {
    console.log("~EvaluateError_" + task.source + "_" + task.commandType + ":");
    return _onError(msg, trace);
  };
  pageGrab.onResourceReceived = function(res) {
    if (task.commandType === "Response") {
      return gbdate = JSON.stringify(res);
    }
  };
  return pageGrab.open(task.url, function(status) {
    if (status !== 'success') {
      task.status = 2;
      task.error = 'Unable to access page';
    } else if (task.commandType === "Response") {
      task.status = 3;
    } else {
      if (!task.withoutJquery) {
        pageGrab.injectJs('jquery-2.1.0.min.js');
      }
      if (task.withUnderscore) {
        pageGrab.injectJs('underscore-min.js');
      }
      pageGrab.injectJs("grabscripts/" + task.source + "_" + task.commandType + ".js");
      gbdate = pageGrab.evaluate(function() {
        return spGrab();
      });
      task.spend = (Date.now() - now) / 1000;
      if (!gbdate) {
        task.status = 2;
        task.error = 'gbdate is false';
      } else {
        task.status = 3;
      }
    }
    pageGrab.close();
    return websocket.evaluate(function(serverUrl, task, data) {
      var taskHub;
      taskHub = $.connection.taskHub;
      taskHub.server.doneTask(task);
      if (task.status !== 2) {
        return $.post(serverUrl + "/task/post" + task.articleType + task.commandType, {
          taskjson: JSON.stringify(task),
          datajson: JSON.stringify(data)
        });
      }
    }, serverUrl, task, gbdate);
  });
};
