// Generated by CoffeeScript 1.7.1
window.spGrab = function() {
  var caps, data, processCap;
  caps = ['吉尼斯杯', '球会友谊', '德甲', '西甲', '意甲', '英超', '法甲', '欧冠', '世界杯', '欧洲杯', '美洲杯', '亚洲杯', '亚冠', '欧联杯', '足总杯', '国王杯', '联赛杯', '意大利杯', '德国杯', '足协杯', '中超', '土伦杯', '慈善盾杯', '解放者杯'];
  data = [];
  processCap = function(capString) {
    if (capString === '球会友谊') {
      capString = '足球友谊赛';
    }
    if (capString === '吉尼斯杯') {
      capString = '国际冠军杯';
    }
    return capString;
  };
  $("#live_Table>tbody>tr:visible[id^='date']").each(function() {
    var day;
    day = $(this).text().split('(')[0];
    return $(this).nextUntil("tr[id^='date'], #gameover").filter(":visible").each(function() {
      var capString, item, quarter;
      capString = $('td', this).eq(1).text();
      if (_.include(caps, capString)) {
        capString = processCap(capString);
        quarter = $('td.state', this).text();
        quarter = quarter.replace('上', '上半场');
        quarter = quarter.replace('下', '下半场');
        quarter = quarter.replace('中', '中场休息');
        item = {
          capString: capString,
          status: 1,
          teamNameChinese: $('td.home>a', this).text(),
          teamNameChineseForGuest: $('td.away>a', this).text(),
          time: Date.parseString(day + $('td.time', this).text(), "yyyy年MM月dd日HH:mm"),
          point: $('td.score span', this).eq(0).text(),
          pointForGuest: $('td.score span', this).eq(1).text(),
          quarter: quarter
        };
        return data.push(item);
      }
    });
  });
  $("#live_Table>tbody>tr#gameover").nextAll("tr:visible").each(function() {
    var capString, datetime, item, time;
    capString = $('td', this).eq(1).text();
    if (_.include(caps, capString)) {
      capString = processCap(capString);
      datetime = new Date();
      time = Date.parseString(day + $('td.time', this).text(), "HH:mm");
      datetime.setHours(time.getHours());
      datetime.setMinutes(time.getMinutes());
      if (datetime > new Date()) {
        datetime.setDate(datetime.getDate() - 1);
      }
      item = {
        capString: capString,
        status: 2,
        teamNameChinese: $('td.home>a', this).text(),
        teamNameChineseForGuest: $('td.away>a', this).text(),
        time: datetime,
        point: $('td.score span', this).eq(0).text(),
        pointForGuest: $('td.score span', this).eq(1).text(),
        quarter: ""
      };
      return data.push(item);
    }
  });
  return data;
};
