// Generated by CoffeeScript 1.7.1
window.spGrab = function() {
  var caps, data, processCap;
  caps = ['吉尼斯杯', '球会友谊', '德甲', '西甲', '意甲', '英超', '法甲', '欧冠', '世界杯', '欧洲杯', '美洲杯', '亚洲杯', '亚冠', '欧联杯', '足总杯', '国王杯', '联赛杯', '意大利杯', '德国杯', '足协杯', '中超', '土伦杯', '慈善盾杯', '解放者杯'];
  data = [];
  processCap = function(capString) {
    if (capString === '球会友谊') {
      capString = '足球友谊赛';
    }
    if (capString === '吉尼斯杯') {
      capString = '国际冠军杯';
    }
    return capString;
  };
  $("#fixture_tb>tbody>tr").not("[id]").each(function() {
    var day;
    day = $(this).text().split('(')[0];
    return $(this).nextUntil("tr:not([id])").each(function() {
      var capString, item;
      capString = $('td', this).eq(0).text();
      if (_.include(caps, capString)) {
        item = {
          capString: processCap(capString),
          status: 0,
          time: Date.parseString(day + $('td', this).eq(1).text().split(' ')[1], "yyyy年MM月dd日HH:mm"),
          teamNameChinese: $('td', this).eq(2).text(),
          teamNameChineseForGuest: $('td', this).eq(4).text()
        };
        return data.push(item);
      }
    });
  });
  return data;
};
