// Generated by CoffeeScript 1.9.2
window.spGrab = function() {
  var data;
  data = [];
  $('#allnews_all>div.items_area>div.item').not(".cooperation").each(function() {
    return data.push($(this).attr('id').replace('J_allItem_', ''));
  });
  return data;
};
