// Generated by CoffeeScript 1.6.3
window.spGrab = function() {
  var contentTags, item;
  item = {};
  item.providerId = window.location.pathname;
  item.sourceLink = window.location.href;
  item.title = $('h1>a').text();
  item.grade = parseInt($("span.comment-big>a").text());
  item.content = "";
  contentTags = $('.time_s').nextUntil('.break');
  $('img[src^="http://tankr.net/"]', contentTags).remove();
  contentTags.each(function() {
    return item.content += $(this).clone().wrap('<div />').parent().html();
  });
  return item;
};
