// Generated by CoffeeScript 1.6.2
window.spGrab = function() {
  var atcul, item, _this;

  _this = $('div.col1:first>.block');
  atcul = _this.children('.bar').children('ul');
  item = {
    content: $.trim(_this.children('.content').html()),
    thumbUps: $.trim($('li', atcul).first().text()),
    thumbDowns: $.trim($('li', atcul).eq(1).text())
  };
  return item;
};
