// Generated by CoffeeScript 1.6.2
window.spGrab = function() {
  var data;

  data = [];
  $('.post>ul>li').slice(0, 9).each(function() {
    var replycount;

    replycount = parseInt($('small:eq(1)>span', this).text());
    if (replycount < 20) {
      return;
    }
    return data.push($(this).children('a').attr('href').replace('http://jandan.net', ''));
  });
  return data;
};
