// Generated by CoffeeScript 1.6.3
window.spGrab = function() {
  var contentTags, item;
  item = {};
  item.providerId = window.location.pathname;
  item.sourceLink = window.location.href;
  item.title = $('h1:eq(1)>a').text();
  item.grade = parseInt($("span.comment-big>a").text());
  contentTags = $('.time_s').nextUntil('.break');
  item.localImages = [];
  $('img[src^="http://tankr.net/"]', contentTags).each(function() {
    item.localImages.push($(this).attr('src'));
    return $(this).attr("src", "http://gptstatic.com/jiandan" + $(this).attr('src').replace(/^[a-zA-Z]+:\/\/[^/]+/g, ''));
  });
  item.content = "";
  contentTags.each(function() {
    return item.content += $(this).clone().wrap('<div />').parent().html();
  });
  return item;
};
