// Generated by CoffeeScript 1.7.1
window.spGrab = function() {
  var embed, item;
  item = {
    KanbisaiLink: window.location.href
  };
  if ($('#liveingArea video').size()) {
    embed = $('#liveingArea').html().trim();
    item.bestVideoMobi = embed;
  }
  return item;
};
