// Generated by CoffeeScript 1.7.1
window.spGrab = function() {
  var embed, item;
  item = {
    KanbisaiLink: window.location.href
  };
  embed = $('#liveingArea').html();
  if (embed) {
    item.bestVideos = embed;
  }
  console.log("bestVideos: " + item.bestVideos);
  return item;
};
