// Generated by CoffeeScript 1.7.1
window.spGrab = function() {
  var data;
  data = [];
  $('div.contentBox').each(function() {
    var ThumbDowns, ThumbUps, atag, item;
    item = {};
    atag = $('li.con_comments', this).children('a');
    item.providerId = atag.attr('href').match(/\d+/g)[0];
    item.sourceLink = "http://www.mimi.me" + atag.attr('href');
    ThumbUps = parseInt($("li.con_like", this).text());
    ThumbDowns = parseInt($("li.con_unlike", this).text());
    item.grade = ThumbUps - ThumbDowns;
    item.content = $(this).children("p").html();
    return data.push(item);
  });
  return data;
};
