// Generated by CoffeeScript 1.7.1
window.spGrab = function() {
  var data;
  data = [];
  $('.tabBox:eq(0)>.tabContents:eq(0) tr').slice(1).each(function() {
    return data.push($(this).children('td').eq(0).children('a').attr('href'));
  });
  return data;
};
