// Generated by CoffeeScript 1.7.1
window.spGrab = function() {
  var data;
  data = {
    capString: $('.live_title').text().trim().split(' ').slice(3).join(' '),
    bestVideoMobi: $('#myMovie>a').attr('href')
  };
  return data;
};
