// Generated by CoffeeScript 1.7.1
window.spGrab = function() {
  var data;
  data = {
    capString: $('.live_title').text().trim().split(' ').slice(3).join(' '),
    bestVideoMobi: $('.videoShow').html().trim()
  };
  return data;
};
