// Generated by CoffeeScript 1.7.1
window.spGrab = function() {
  var data;
  data = {};
  data.capString = $('#zbb_path>ul>li').last().text().trim().split(' ').slice(3).join(' ');
  data.bestVideo = $('#v_player>a').attr("href");
  return data;
};
