// Generated by CoffeeScript 1.7.1
window.spGrab = function() {
  var data;
  data = {};
  if ($('.videoShow a').size()) {
    data.transferData = $('.videoShow a').attr("href");
  } else {
    data.transferData = $('.videoShow').html().trim();
  }
  return data;
};
